# Generated by Django 5.2 on 2025-05-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
